name: Build (macOS/Windows/Linux)

on:
  push:
    tags: ['v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Verify Node & NPM in PATH
        run: |
          node -v
          npm -v

      - name: Cache electron caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      # ---------- Install deps per OS ----------
      - name: Install deps (macOS/Linux)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Install deps (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          if (Test-Path "package-lock.json") {
            npm ci
          } else {
            npm i
          }

      # ---------- Build per OS ----------
      - name: Build macOS
        if: runner.os == 'macOS'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run dist:mac

      - name: Build Windows
        if: runner.os == 'Windows'
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run dist:win

      - name: Build Linux
        if: runner.os == 'Linux'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'
        run: npm run dist:linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: dist/**
          if-no-files-found: error
          retention-days: 14
